### ISSUE TITLE
Can we have a "MNIST" visualization tutorial ?

### ISSUE THREAD

**Issue by astrung** [InFoCusp/tf_cnnvis#13]
I am beginner with tensorflow and CNN. So can we have a tutorial about how to use it ?

**Comment by BhagyeshVikani** [comment]
We have a example-2 which include training of CNN using MNIST dataset. You can take a look at it and if you have any question we are glad to help.

**Comment by BhagyeshVikani** [comment]
I am closing this issue. But feel free to ask any question you had.
