### ISSUE TITLE
Is it possible to only visualize one layer?

### ISSUE THREAD

**Issue by ranranking** [InFoCusp/tf_cnnvis#17]
by using the `deconv_visualization()` function, it generates deconv images for each layers by default. Is it possible to only generate images for one single layer? Thank you.

**Comment by BhagyeshVikani** [comment]
Hello @ranranking,

Yes. You can generate deconv images for only a specific layer by passing it in `layers` argument.
Ex. If you want to generate deconv images for `fc8` layer then pass `layers=['fc8']`.

Thank You

**Comment by ranranking** [comment]
@BhagyeshVikani Thank you very much for the help! It works!

**Comment by princeco** [comment]
hello i want to know whether this tool support fc layer or not, i find it only support pooling,rely,and cone layer..
