### ISSUE TITLE
Quickfix for Python 3.x setup.py UnicodeDecodeError

### ISSUE THREAD

**Issue by hi-im-ryanli** [InFoCusp/tf_cnnvis#18]
In setup.py, change function `read()` to the following:

```python
def read(fname):
	if six.PY2:
		return open(os.path.join(os.path.dirname(__file__), fname)).read()
	else:
		return open(os.path.join(os.path.dirname(__file__), fname), encoding='latin1').read()
```

This will fix the issue if some users in Python 3.X encounter UnicodeDecodeError during the installation 👍

**Comment by falaktheoptimist** [comment]
Could you please provide some details on which platform you're seeing this error? 
And how does latin1 encoding help with resolving that error? Because the ReadMe file can be opened and read in python3 with the same open command.

**Comment by hi-im-ryanli** [comment]
Yes - it's a Windows running Python 3.5. 

Screenshot of running `setup.py` from master:
![screenshot_2](https://user-images.githubusercontent.com/10702581/32186052-fb288320-bd6e-11e7-904e-6a23152c8f49.png)

After encoding change, installation is successful.
![screenshot_1](https://user-images.githubusercontent.com/10702581/32186141-493384f2-bd6f-11e7-885f-0e1e2c2999e1.png)

**Comment by falaktheoptimist** [comment]
Alright, Thanks for the update. Would you like to send in a PR? Or we could make the change ourselves.
