### ISSUE TITLE
How to generate bigger images

### ISSUE THREAD

**Issue by camer314** [InFoCusp/tf_cnnvis#21]
On your homepage you have large images but when i run the code the grid is 8x8 = 254px*254px, how can i generate larger images?

Also does it have to generate the grid, can i get it to generate a file for each image?

**Comment by falaktheoptimist** [comment]
Hi @camer314 
In the Tensorboard output, we have both the complete grid as output as well as individual images. You simply need to switch from all at once to One by one to view individual images.

Thanks!

**Comment by camer314** [comment]
ok thanks
