### ISSUE TITLE
Running deep dream gives error "invalid argument: computed output size would be negative"

### ISSUE THREAD

**Issue by camer314** [InFoCusp/tf_cnnvis#22]
As per the title, when i run the sample 3 using inception5 and the image of the wolf and use deepdream_visualization i end up getting this error over and over again.

Any ideas as to why?

**Comment by falaktheoptimist** [comment]
This is a warning in TensorFlow which might be shown in  the jupyter-notebook terminal. It should not affect the implementation and you'll be able to see the output in TensorBoard. We'll work on getting to the bottom of it and getting rid of the warning, but it isn't a showstopper and should work for now.

**Comment by camer314** [comment]
Yes sorry, I should have let it run for longer, that is fine thanks
