### ISSUE TITLE
how to visualize network with BN?

### ISSUE THREAD

**Issue by baodingge** [InFoCusp/tf_cnnvis#23]
my network was trained from scratch, so i use some BN layer.Should I modify the BN layer gradient?

**Comment by falaktheoptimist** [comment]
Hi @baodingge 
Yes, you're right - you'll need to modify the gradient for batch normalization. We have included a case for layer normalization but not for batch normalization. 

However, we shuould have a similar case for batch normalization too - one that simply passes back the gradient that comes in from the succeeding layer to the preceding one. If you do make a change in tf_cnnvis, send us a PR and we'll merge or, we'll add the required case in a few days.

Thanks!

**Comment by baodingge** [comment]
Yes, I use the code without change the code, it also works well, and it looks a bit grey,but it is useful.
![conv6_2](https://user-images.githubusercontent.com/23653105/33262112-1b08a142-d3a0-11e7-91a0-aed5807d9673.png)

**Comment by falaktheoptimist** [comment]
Alright. Thanks for the update. Applying Histogram equalization on the above image might get you an even better output.
