### ISSUE TITLE
visualization for semantic segmentation task is possible?

### ISSUE THREAD

**Issue by smajida** [InFoCusp/tf_cnnvis#24]
Hi, 

i have mostly seen people use visualization for image recognition models. Does it make sense and is it possible to use your code for visualizing FCN network layers?

**Comment by falaktheoptimist** [comment]
Hi @smajida 
Yes, it is most certainly possible. We had that in mind when designing tf_cnnvis, so we do have provision for fully connected network too. This will show you a kind of heatmap of the reconstructed input- indicating which nodes are more important. This is the closest thing we could think of, as reconstructing "image" per se is not an option for 1-d inputs. We have tested a simple case for activation visualization. 
If you use it in a prototype model which can be shared, please share or add a notebook in the examples.
Thanks!

**Comment by smajida** [comment]
@falaktheoptimist thanks for your response I am working on it with my colleague. I will update you as soon as I have something to show.
