### ISSUE TITLE
Example of using Inception v3

### ISSUE THREAD

**Issue by camer314** [InFoCusp/tf_cnnvis#25]
Are you able to provide a sample on the best practice for feeding an image into a Inception3 model.

At the moment I have:

	t_input = tf.placeholder(tf.uint8, name='input')
	image = Image.open(imageFileName)
	im = np.array(image)[:, :, 0:3] 
	tf.import_graph_def(graph_def, {'DecodeJpeg:0': t_input})

This works but in your sample for Inception5h you resize the image at the same time, due to the different input types between v3 and v5 I am not sure how to get the equivilent behaviour

**Comment by falaktheoptimist** [comment]
Hi @camer314 

I am not very clear what the question is here, but I'll take a stab at answering anyways.
So, if you want to resize the image that you read from disk and resize it, you can use the command we have in example of v5: `im = np.expand_dims(imresize(imread(os.path.join("./sample_images", "images.jpg")), (224, 224)), axis = 0)` This returns a resized numpy array containing images. With this, you won't need to use the image and im variables above. 

However, if you want to convert input type as you mentioned in the question, you can simply use tf,float32 insteat of tf.uint8 and divide the resulting tensor by 255: `t_input = tf.placeholder(tf.float32, name='input')/255.0`

**Comment by falaktheoptimist** [comment]
closing this for now. Reopen if unresolved.

**Comment by UndecidedBoy** [comment]
Hello, 

I just wanted to know if I need to keep my image type to uint8 when using :
 ```
activation_visualization(sess_graph_path=sess, value_feed_dict={X: im},
                                              layers=layers, path_logdir=os.path.join("Log", "AlexNet"),
                                              path_outdir=os.path.join("Output", "AlexNet"))
```
Or can I convert it to a float.32 before feeding it to the function ?
I tested both ways and they didn't give me the same results. I presume that a conversion is done at some point in the function?

In the meantime, thanks for your time and efforts.
