### ISSUE TITLE
Have some question about generate folder

### ISSUE THREAD

**Issue by xiongfeiliu** [InFoCusp/tf_cnnvis#27]
hi
 I run successfully and generate some folders but I don't understand what is conv2d-conv2d_7

**Comment by falaktheoptimist** [comment]
Hi @xiongfeiliu 
conv2d_7 refers to the 7th 2d convolution layer. It'll be the same name as in the model you created in TensorFlow.

**Comment by xiongfeiliu** [comment]
Hi @falaktheoptimist 
I mean Alexnet only have 5 conv layers But my result generate another folders named conv2d,cond2d_1.....conv2d_7 I don't understand how they come

**Comment by falaktheoptimist** [comment]
They could have been present from before you constructed the actual graph (This happens commonly in notebooks). Use tf.reset_default_graph() at beginning if you're using notebook.

**Comment by xiongfeiliu** [comment]
Thank you I will try @falaktheoptimist
