### ISSUE TITLE
Running the tf_connvis_example1.ipynb ，then having a error

### ISSUE THREAD

**Issue by panhu** [InFoCusp/tf_cnnvis#29]
hi ,when i running the example,generating a error ：

OSError: [Errno 22] Invalid argument: './Out/AlexNet\\conv1\\image_2017-12-22_10:16:21\\activations\\grid_activation.png'

**Comment by falaktheoptimist** [comment]
Hi!
It's simply a Windows vs Ubuntu thing. Thanks for bringing this to our notice. You'll need to change it to `.\Output\AlexNet` for Windows. We'll make the change to make it generic in the notebook and commit soon.
Thanks!

**Comment by falaktheoptimist** [comment]
https://github.com/InFoCusp/tf_cnnvis/commit/6593dbc603be3d268fb77f026e722d7c22adf5d1 #
