### ISSUE TITLE
example2  Session and vaiabale re-initialization

### ISSUE THREAD

**Issue by csggnn** [InFoCusp/tf_cnnvis#30]
I am using this project and am going trough example2 on MNIST data to get a better grasp on how tensorflow and cnn visualization works. I apologize in advance if I am missing some trivial aspect and my question is not relevant. 

To my understanding, block 3 in example2 trains a cnn on MNIST data to learn weights and block 4 uses tf_cnnvis functions to inspect what the network has learned. The training is performed in a `with tf.Session() as sess:` block, while a new `Session `and subsequent  `tf.global_variables_initializer()` call is issued in `_visualization_by_layer_name` within `deconv_visualization`.

Would this not wipe off the weights learned in training?

**Comment by falaktheoptimist** [comment]
Hi @csggnn 
Great catch! Would you like to make the change (move it to within the session) and submit a PR. Or we'll make the change from our end soon.

Thanks!

**Comment by csggnn** [comment]
Thanks! I would like to try and make the change, anyhow it may have more impact then I originally thought. `tf.global_variables_initializer()` is called in `_visualization_by_layer_name` which is used by all visualizations and examples.
To solve the problem I would pass session as optional argument to the 3 interface visualization functions, and resort on `tf.get_default_session()` as a fallback when session is not passed and visualization functions are called within a `with sess.as_default():` block.
I'll try to propose my fix and you'll decide whether to use it or to start from scratch with your own.
I would anyhow love to make some more questions directly to make sure I don't miss out something in the project's way of working (mainly on the  `_save_model(graph)`  part).
Please contact me directly if you will, my mail is in my profile.

**Comment by falaktheoptimist** [comment]
We have now added a check to ensure that the graph doesn't contain any variables. Thanks again for finding and helping fix this bug.
