### ISSUE TITLE
how to use this on audio data?

### ISSUE THREAD

**Issue by manbharae** [InFoCusp/tf_cnnvis#37]
I am computing mfcc for audio file, andtrain a cnn. How do I visualize what the network is learning at different layers?

**Comment by falaktheoptimist** [comment]
Hi!
MFCC, to the best of our understanding should produce a 2 dimensional short duration power spectrum. You can input this just as an image into tf_cnnvis. This should provide you with an idea about which of the MFCC features are important to activate which CNN layers. Let us know if you hit any roadblocks. Also, please do share the results you get/ create a short notebook example. That would be useful for other users using this for audio data.

Thanks!

**Comment by falaktheoptimist** [comment]
Am closing this.. Please point re-open if still unresolved.
