### ISSUE TITLE
how to use other CNN architecture(for example VGG,GOOGLENET...) to implement visualization?

### ISSUE THREAD

**Issue by LongruiDong** [InFoCusp/tf_cnnvis#43]
Hi~
very thankful for you nice work! I am kind of  new to tensorflow, I have run _tf_cnnvis_Example1.ipynb_ successfully and  I am wondering how to replace AlexNet with some other pretrained CNN architecture (for example ,VGG) 
hope to get your response~
appreciate it a lot

**Comment by falaktheoptimist** [comment]
Hi!
Have a look at example 3 - it uses inception network by google. You can use any of your pretrained network instead. Just replace it with your own pb file.

**Comment by BhagyeshVikani** [comment]
Closing this one. Reopen if needed.
