### ISSUE TITLE
Some points unclear and references missing

### ISSUE THREAD

**Issue by prmadhu** [InFoCusp/tf_cnnvis#5]
Hey,

There are a few points which seem to be unclear for understanding. Maybe you could explain a few things briefly or add some references to the README.md file. That would be helpful, thanks. 

Cheers.

**Comment by falaktheoptimist** [comment]
Readme updated with deepdream explanation https://github.com/InFoCusp/tf_cnnvis/commit/9adae3d8fa47cba9d3f62a7f35566bb27c41b144
