### ISSUE TITLE
Can someone give me steps to try out this toolbox on my own model?

### ISSUE THREAD

**Issue by Akhil-Raj** [InFoCusp/tf_cnnvis#53]
I have a trained tensorflow model that I want to visualize. Can someone tell me how to do so? Which files to edit. I have seen the three examples given but I can't infer how to do so on my model.
If any details are required, kindly ask.

**Comment by BhagyeshVikani** [comment]
Please have a look at the examples in the repository: https://github.com/InFoCusp/tf_cnnvis/tree/master/examples 
After browsing through those, if you still have any doubts, we'll be happy to answer.
