### ISSUE TITLE
No attribute _relu_grad

### ISSUE THREAD

**Issue by NullConvergence** [InFoCusp/tf_cnnvis#54]
Hello there, I've tried to run the examples using tensorflow v1.8.0 on ubuntu 16.04 and macOS High Sierra, python v3, but I get the following error:

example_1, method 'deconv_visualization': AttributeError: module 'tensorflow.python.ops.gen_nn_ops' has no attribute '_relu_grad'

I investigated a bit and it seems that gen_nn_ops is generated by basel. I think the error comes from a difference in versions. Should we try to update the code to the latest versions?

**Comment by BhagyeshVikani** [comment]
Hello @NullConvergence 

Please look at this issue #50 .

**Comment by NullConvergence** [comment]
Hi @BhagyeshVikani: Great! why don't you integrate this fix in a new version?

**Comment by falaktheoptimist** [comment]
Done
