### ISSUE TITLE
Examples do not replicate description results?

### ISSUE THREAD

**Issue by GrigoriiTarasov** [InFoCusp/tf_cnnvis#57]
Hello!

In description:
"Figure 1: Original image and the reconstructed versions from maxpool layer 1,2 and 3 of Alexnet generated using tf_cnnvis."
![3](https://user-images.githubusercontent.com/20603530/42737002-e0fd3430-8877-11e8-8aeb-106c7a96ce37.png)

After running tf_cnnvis_Example1.ipynb got deconvolutions folders with grided images, with
non of the picture from the grid seems to be a deconvolution image as in description.  

The most look-like image from maxpool_3/deconvolution is:

![deconv_75](https://user-images.githubusercontent.com/20603530/42736960-41e41e90-8877-11e8-888d-d07d26353e0d.png)

The most look-like image from maxpool_4/deconvolution is:

![deconv_112](https://user-images.githubusercontent.com/20603530/42736985-9ef49d94-8877-11e8-8262-d69cacdfc265.png)

Is there a way get the same picture as in description with your tool?

**Comment by falaktheoptimist** [comment]
Hi @GrigoriiTarasov 
I am getting very similar images to the ones we posted under AlexNet/maxpool_4. However, if you want really sharp images, the `Contrast adjustment` would help - it is available in tensorboard on the left side bar. However, if you are getting very garbled images, there must be some problem with your setup. Please re test if it works. Attaching a screenshot
![contrast](https://user-images.githubusercontent.com/7119249/44033210-4d3aeb18-9f27-11e8-8906-978ca0b859bf.png)

**Comment by falaktheoptimist** [comment]
Closing this one. Reopen if needed.
