### ISSUE TITLE
Questions about the name 'All_At_Once_Activations' in the tensorboard ?

### ISSUE THREAD

**Issue by douhaoexia** [InFoCusp/tf_cnnvis#60]
thank you for your pretty work.
I have run the example 1 and get the visiualization on the tensorboard.
Could you explain the meaning of ' All_At_Once_Activations '  , ' All_At_Once_Deconv ' and 'One_By_One_Deconv ' ?

**Comment by jidebingfeng** [comment]
Most layer have more than one filters. All filters results of one layer in one image is `ALL_At_Once`. Different filter result in different image is `One_By_One`.
I think `Activations` is the result of Forward Propagation. And `Deconv ` show that, what is interested content of the filter.

**Comment by falaktheoptimist** [comment]
That's a perfect explanation. Thanks @jidebingfeng. Closing this- reopen if you have any questions @douhaoexia

**Comment by jidebingfeng** [comment]
@falaktheoptimist I search this repository, because I believe that CNN similar with human to classify images. Human judge a horse from it's features like four legs, long tails and so on. For human, training features isn't necessary option to classify horse . The features many from cow classification or some other animals classification. Why features must be in one model? I think a feature of horse can be from a cow model.  Does your team has any research on this?

**Comment by jidebingfeng** [comment]
Pardon me for this question. I think my question is relation to `CNNVis `.

**Comment by falaktheoptimist** [comment]
Hi @jidebingfeng 
That's an excellent question. I'll try to address this  - so, yes you are right - CNNs are learning overall features which are very similar to what humans use to classify images. So, it would be the overall shape and parts for animals like cow, horse, etc. The difference is that at the lower or initial layers, it learns very low level features - that is it identifies edges, corners and so on and then goes on to combine these low level features into a more solid shape as we move to higher layers. Also, these features are generated by using filters present in the CNN. 
Now, something common across classes such as 4 legs, horns, etc. would be learnt by the features. And the very last layers, it would actually learn how to separate those features into the classes. So, the 4 legs might be common to both cow and horse but the tail shape might be useful for separating those 2 categories. Hope this answers your question to some extent. For more details, you can look at this paper: https://cs.nyu.edu/~fergus/papers/zeilerECCV2014.pdf or even the course CS231n :http://cs231n.stanford.edu/syllabus.html which would give much deeper insights into this.
