### ISSUE TITLE
Black squares in deconv results

### ISSUE THREAD

**Issue by skateskate** [InFoCusp/tf_cnnvis#61]
Hello,
I have some doubts regarding the interpretation of the results I am getting from the deconvolution. My network basically repeats four times two convolutional layers followed by one pooling layer, and the deconvolutional outputs are extracted from the end of each pooling layer. I'm working with mel-spectrogram as input images, and I am trying to predict the predominant instruments in a song.

As you can see in the attached files, each image shows the recontructed input for each filter (32-64-128-256 filters respectively). Unfortunally, in the last two layers I have several black squares where it seems that the deconvolution can't reconstruct any input. 

Do you know why I am getting this? Do you think that can be a problem somewhere in my network?

[deconv_res.zip](https://github.com/InFoCusp/tf_cnnvis/files/2261576/deconv_res.zip)

**Comment by falaktheoptimist** [comment]
Hi @skateskate 
Glad to see this tool being used in different domains. The deconvolution output indicates what input was responsible for generating the output at a particualr channel in a particular layer. In your case, I suspect that either the filter weights for that particular channel are very low, thus leading to a black or low output. Or a second, more likely possibility is that the relu layer is blackening out negative values to zero. This would mean that the activation output at that layer would also be low. You can check this by checking the activation outputs - if that is dark/ black too, then that particular activation  does stay off / black for that layer and there is not a problem with the model.

**Comment by skateskate** [comment]
Hello @falaktheoptimist, 
first of all thank you for your clear explanation. I agree with your opinion and, in the past few days, I tried to change the input mel-spectrogram to see if the output black squares change their position in the grid.
Fortunally they do, meaning that those particular channels weren't activated from that particular input, so I think that this is a typical behavior of my network.

Thanks again for your time.

**Comment by falaktheoptimist** [comment]
Cool! Glad it was useful. Thanks for clearing this up.
