### ISSUE TITLE
Exporting of visualizations?

### ISSUE THREAD

**Issue by rhettdsouza13** [InFoCusp/tf_cnnvis#63]
Currently, can the visualizations be exported as images to a local path, after they are generated?
Right now, they can only be visualized on Tensorboard, right?
If not, is the team working on implementing it? Is there a way to already do it that I'm missing?
Thanks in advance for the help or addressing of the  "issue"!!

**Comment by falaktheoptimist** [comment]
They are being written to disk by default. There's an input argument in the API: path_outdir='./Output' This is where the output images are being stored on disk.

**Comment by falaktheoptimist** [comment]
Closing this one since it's resolved. Reopen if needed.

**Comment by rhettdsouza13** [comment]
Okay! Thank you. I was unsure about the writing-to-file scheme.

Thank you
