### ISSUE TITLE
Visualisation for InceptionV4

### ISSUE THREAD

**Issue by Sapan2307** [InFoCusp/tf_cnnvis#65]
First of all, thank you for implementing this. It works great for AlexNet. I am new to this field so sorry if you do not find question appropriate.

I have downloaded inception v4 weights in .h5 file. Even tried to understand the structure of layers in it. I think visualisation in inception v4 required drastic code modification. Is there any short-cut? Can you help me for implementing visualisation of InceptionV4? 

I am actually interested more in knowing filters, which play most important role for classification. Like out of 128 filters on convolution layer, which 10 are actually make my classification done. Can we do this by Visualisation in "Visualising and understand CNN" method?

**Comment by falaktheoptimist** [comment]
Reopen if you have any further questions
