### ISSUE TITLE
why I always meet this problem?

### ISSUE THREAD

**Issue by daixiaogang** [InFoCusp/tf_cnnvis#9]
Here's the error I'm getting

`ValueError: Cannot feed value of shape (1, 224, 224, 3) for Tensor u'Placeholder:0', which has shape '(2, 224, 224, 3)'` 

Here's the code for reproducing the error:

------------------------------------------------
`images = tf.placeholder("float", [2, 224, 224, 3])
batch1 = img1.reshape((1, 224, 224, 3))
batch2 = img2.reshape((1, 224, 224, 3))
batch = np.concatenate((batch1, batch2), 0)
feed_dict = {images: batch}
is_success = activation_visualization(graph_or_path=tf.get_default_graph(),value_feed_dict={X:batch},layers='r')`

-------------------------------------------------------
Network is vgg16

**Comment by BhagyeshVikani** [comment]
You already define feed_dict but you again define it while calling. Try this solution:
## is_success = activation_visualization(graph_or_path=tf.get_default_graph(),value_feed_dict=feed_dict,layers='r')

**Comment by daixiaogang** [comment]
thanks,I have solved this problem!
